### ISSUE TITLE
CRUD in a diary

### ISSUE THREAD

**Issue by genelorenzSarmiento0408** [chingu-voyages/v40-toucans-team-10#14]
**__Feature Description__**
We should accomplish CRUD (Creating, Reading, Updating, Deleting) a diary/diaries

**__Major User Stories/tasks__**
- [x] Users can write the diary using the Markdown format with Title and Description
- [x] A user can read a diary with both the title and the description
- [x] The diary/diaries will be saved, even when a user exits it
- [x] The user can edit a diary of their own
- [x] The user can delete the diary/note that they had created

**__Additional Considerations__**
External Resources:
[Almost the same app using similar user stories/tasks](https://github.com/florinpop17/app-ideas/blob/master/Projects/1-Beginner/Notes-App.md)
